module.exports.READY_FOR_REVIEW = 'ready for review'
module.exports.REJECTED = 'rejected'
module.exports.REVIEW_REQUESTED = 'review requested'
module.exports.IN_PROGRESS = 'in progress'
module.exports.SECURITY = 'security'
